-- 코드를 입력하세요
-- 1. 도서 판매 데이터 기준
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, T.CATEGORY, T.TOTAL_SALES
FROM AUTHOR A
JOIN (
    SELECT B.AUTHOR_ID, 
           B.CATEGORY, 
           SUM(S.SALES * B.PRICE) AS TOTAL_SALES
    FROM BOOK_SALES S
    JOIN BOOK B
    ON S.BOOK_ID = B.BOOK_ID
    WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY B.AUTHOR_ID, B.CATEGORY
) T
ON A.AUTHOR_ID = T.AUTHOR_ID
ORDER BY A.AUTHOR_ID, T.CATEGORY DESC;