-- 코드를 입력하세요
-- 저자 별 + 카테고리 별 매출액 ->
-- BOOK & BOOK_SALES 먼저 조인
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, S.CATEGORY, S.TOTAL_SALES
FROM AUTHOR A
JOIN(
    -- 카테고리별 + 작가별 매출액
    SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
    FROM BOOK B
    JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
    WHERE BS.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY B.CATEGORY, B.AUTHOR_ID
) S
ON A.AUTHOR_ID = S.AUTHOR_ID
ORDER BY A.AUTHOR_ID, S.CATEGORY DESC;