-- 코드를 입력하세요
-- 테이블에서 년, 월, 성별 별로 상품을 구매한 회원수 
-- 1. 년도
/*
SELECT YEAR(SALES_DATE) AS YEAR, COUNT(SALES_AMOUNT) AS COUNT
FROM ONLINE_SALE
GROUP BY YEAR;
*/

-- 2. 월별
/*
SELECT MONTH(SALES_DATE) AS MONTH, COUNT(SALES_AMOUNT) AS COUNT
FROM ONLINE_SALE
GROUP BY MONTH;
*/

-- 3. 성별 
SELECT 
    YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH,
    I.GENDER, 
    COUNT(DISTINCT O.USER_ID) AS USERS
FROM ONLINE_SALE O
JOIN USER_INFO I
ON I.USER_ID = O.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, I.GENDER
ORDER BY YEAR, MONTH, I.GENDER;






