-- 코드를 입력하세요
-- ANIMAL_OUTS 테이블에는 있으면서, ANIMAL_INS에 없는 데이터 
-- 동명의 동물 있을 수도 있음 
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE O.ANIMAL_ID NOT IN(
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
);