-- 코드를 입력하세요
-- 아직 입양을 못 간 동물 중, 가장 오래 보호소에 있었던 동물 
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.ANIMAL_ID NOT IN(
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
)
ORDER BY I.DATETIME
LIMIT 3;