-- 코드를 입력하세요
-- 7월 아이스크림 총 주문량 
SELECT FLAVOR
FROM (
    SELECT J.FLAVOR, SUM(J.TOTAL_ORDER + S.TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY J
    JOIN(
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF
        GROUP BY FLAVOR
    ) S
    ON J.FLAVOR = S.FLAVOR
    GROUP BY J.FLAVOR
    ORDER BY TOTAL_ORDER DESC
    LIMIT 3
) T;

/*
SELECT J.FLAVOR, SUM(J.TOTAL_ORDER + S.TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY J
JOIN(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
) S
ON J.FLAVOR = S.FLAVOR
GROUP BY J.FLAVOR
ORDER BY TOTAL_ORDER DESC
LIMIT 3;
*/

