-- 코드를 입력하세요
-- FIRST_HALF : 상반기 주문 정보 
-- JULY : 7월 주문 정보
-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서 
/*
SELECT J.FLAVOR
FROM JULY J
LEFT JOIN FIRST_HALF F
ON J.SHIPMENT_ID = F.SHIPMENT_ID
WHERE J.
*/

-- 7월 주문량 + 상반기 주문량 
/*
SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) + S.TOTAL_ORDER AS TOTAL_ORDER
FROM JULY J
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
) S
ON J.FLAVOR = S.FLAVOR
GROUP BY J.FLAVOR
ORDER BY TOTAL_ORDER DESC
LIMIT 3;
*/

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) J ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.JULY_TOTAL) DESC
LIMIT 3;