-- 코드를 입력하세요
-- 1. 해당 날짜에 취소 x

SELECT 
    A.APNT_NO, 
    P.PT_NAME, 
    A.PT_NO, 
    A.MCDP_CD, 
    D.DR_NAME, 
    A.APNT_YMD
FROM APPOINTMENT A
JOIN PATIENT P 
    ON A.PT_NO = P.PT_NO
JOIN DOCTOR D
    ON A.MDDR_ID = D.DR_ID
WHERE APNT_CNCL_YN = 'N' AND DATE(APNT_YMD) = '2022-04-13'
ORDER BY A.APNT_YMD;
