-- 코드를 입력하세요
-- 완료된 중고 거래의 + 총 금액이 70만원 이상
-- 서브쿼리에서 70만원 이상만 남기기 

SELECT U.USER_ID, U.NICKNAME, S.TOTAL_PRICE AS TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_PRICE
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_PRICE >= 700000
) S
ON U.USER_ID = S.WRITER_ID
ORDER BY TOTAL_SALES;

