-- 코드를 입력하세요
-- 해당 기간 동안 대여 횟수가 5회 이상인 자동차들
SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN(
    SELECT CAR_ID, COUNT(*) AS COUNTS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNTS >= 5
) S
ON C.CAR_ID = S.CAR_ID
WHERE C.START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, C.CAR_ID
ORDER BY MONTH, C.CAR_ID DESC;

