-- 코드를 입력하세요
-- 조회수가 가장 높은 중고거래 게시물의 경로 
SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/', A.FILE_ID, A.FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE A
WHERE A.BOARD_ID = ( 
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
ORDER BY FILE_ID DESC;


/*
SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/', A.FILE_ID, A.FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE A
JOIN (
    SELECT BOARD_ID, MAX(VIEWS)
    FROM USED_GOODS_BOARD
) B
ON A.BOARD_ID = B.BOARD_ID
ORDER BY FILE_ID DESC;
*/




