-- 코드를 입력하세요
-- 2022년 1월의 카테고리 별 도서 판매량 
SELECT A.CATEGORY, SUM(S.BOOK_ID_SALES) AS TOTAL_SALES
FROM BOOK A
-- 2022년 1월 도서 중 각 책별로 몇 권 팔렸는지 
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS BOOK_ID_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN ('2022-01-01') AND ('2022-01-31')
    GROUP BY BOOK_ID
    ) S
ON A.BOOK_ID = S.BOOK_ID
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY;


-- 책 아이디별 도서 판매량
/*
SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES
GROUP BY BOOK_ID;
*/